services:
  rest:
    build:
      context: ./rest
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./logs:/app/logs

  calculator:
    build:
      context: ./calculator
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    volumes:
      - ./logs:/app/logs

networks:
  my-network:
    driver: bridge
